# Generated by Django 4.1 on 2022-08-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lleno', models.BooleanField(default=True)),
                ('marcaDeEmpresa', models.CharField(max_length=100)),
                ('Tipo', models.CharField(max_length=100)),
            ],
        ),
    ]
