# Generated by Django 4.1 on 2022-08-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('recibo_honorarios', models.IntegerField()),
                ('pago', models.DecimalField(decimal_places=5, max_digits=100)),
            ],
        ),
    ]
